FROM centos:latest
MAINTAINER rose <qrataller@tip.edu.ph>

# To skip prompts
arg debian_frontend=noninteractive

# To update packages
run yum update; yum upgrade -y

# to install package
run yum install -y httpd mariadb-server

# To set an entrypoint
entrypoint usr/sbin/httpd -d foreground
